name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: npm install

      # - name: Build Next.js app
      #   run: npm run build

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: 141.148.163.55
          username: opc
          key: id_ed25519
          script: |
            whoami
            ls -lah
